#!/usr/bin/env python3
"""check-source-health.py — URL liveness checking for source URLs.

Opt-in via config.source_authority.health_check.enabled (default: false).
Checks URLs from instance/sources.yaml and wiki frontmatter, classifies
as healthy/gone/redirected, appends to instance/state/source-health.yaml.
v1: liveness only; excerpt drift deferred to v2.

Usage:
  python3 .sprue/scripts/check-source-health.py            # human-readable
  python3 .sprue/scripts/check-source-health.py --quiet    # exit code only
  python3 .sprue/scripts/check-source-health.py --json     # structured output
"""
from __future__ import annotations

import argparse, json as jsonlib, ssl, sys, urllib.request, urllib.error
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urlparse

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
from config import load as load_config
from lib import find_wiki_pages, parse_frontmatter

sys.path.insert(0, str(Path(__file__).resolve().parents[3]))  # adds src/
from sprue.engine_root import instance_root

WIKI = instance_root() / "wiki"
SOURCES_FILE = instance_root() / "instance" / "sources.yaml"
HEALTH_LEDGER = instance_root() / "instance" / "state" / "source-health.yaml"


def _collect_urls() -> set[str]:
    """Deduplicated source URLs from sources.yaml and wiki page frontmatter."""
    urls: set[str] = set()
    # Pool 1: instance/sources.yaml (may not exist)
    if SOURCES_FILE.exists():
        for entries in (yaml.safe_load(SOURCES_FILE.read_text()) or {}).values():
            if isinstance(entries, list):
                urls.update(e["url"] for e in entries if isinstance(e, dict) and e.get("url"))
    # Pool 2: wiki page frontmatter sources[].url
    if WIKI.is_dir():
        for page in find_wiki_pages(WIKI):
            fm, _ = parse_frontmatter(page)
            urls.update(s["url"] for s in (fm.get("sources") or []) if isinstance(s, dict) and s.get("url"))
    return urls


def _check_url(url: str, timeout: int) -> dict:
    """HTTP HEAD (fallback GET) liveness check. Returns health record."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    ctx = ssl.create_default_context()
    rec = {"url": url, "checked_at": now}
    for method in ("HEAD", "GET"):
        try:
            req = urllib.request.Request(url, method=method, headers={"User-Agent": "sprue-health/1.0"})
            resp = urllib.request.urlopen(req, timeout=timeout, context=ctx)
            final = resp.geturl()
            # Cross-domain redirect → redirected
            if urlparse(final).netloc != urlparse(url).netloc:
                rec.update(status=resp.status, category="redirected", details=f"Redirected to {final}")
                return rec
            rec.update(status=resp.status, category="healthy", details="OK")
            return rec
        except urllib.error.HTTPError as e:
            if method == "HEAD" and e.code == 405:
                continue  # HEAD not allowed — fall back to GET
            rec.update(status=e.code, category="gone", details=f"HTTP {e.code}")
            return rec
        except (urllib.error.URLError, OSError, TimeoutError) as e:
            if method == "HEAD":
                continue  # Network issue on HEAD — try GET
            rec.update(status=0, category="gone", details=str(getattr(e, "reason", e)))
            return rec
    rec.update(status=0, category="gone", details="HEAD and GET both failed")
    return rec


def _append_ledger(results: list[dict]) -> None:
    """Append results to health ledger (append-only per platform state model)."""
    HEALTH_LEDGER.parent.mkdir(parents=True, exist_ok=True)
    existing = yaml.safe_load(HEALTH_LEDGER.read_text()) or [] if HEALTH_LEDGER.exists() else []
    existing.extend(results)
    with open(HEALTH_LEDGER, "w", encoding="utf-8") as f:
        f.write("# Source health ledger — append-only, auto-generated by check-source-health.py\n")
        yaml.dump(existing, f, default_flow_style=False, allow_unicode=True, sort_keys=False)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--quiet", action="store_true", help="Suppress output, exit code only")
    ap.add_argument("--json", action="store_true", help="JSON output")
    args = ap.parse_args()

    cfg = load_config()
    hc = cfg.get("source_authority", {}).get("health_check", {})

    # Opt-in: exit 0 if disabled
    if not hc.get("enabled", False):
        if not args.quiet and not args.json:
            print("⏭️  Source health check disabled (config.source_authority.health_check.enabled: false)")
        elif args.json:
            print(jsonlib.dumps({"skipped": True, "reason": "health_check disabled"}))
        return 0

    urls = _collect_urls()
    if not urls:
        if not args.quiet and not args.json:
            print("✅ No source URLs found to check.")
        elif args.json:
            print(jsonlib.dumps({"results": [], "summary": {"total": 0}}))
        return 0

    results = [_check_url(u, hc.get("timeout_seconds", 10)) for u in sorted(urls)]
    _append_ledger(results)

    counts = {"healthy": 0, "gone": 0, "redirected": 0}
    for r in results:
        counts[r["category"]] = counts.get(r["category"], 0) + 1
    has_issues = counts["gone"] > 0 or counts["redirected"] > 0

    if args.json:
        print(jsonlib.dumps({"results": results, "summary": counts}, indent=2))
    elif not args.quiet:
        print(f"Source health: {counts['healthy']} healthy, {counts['gone']} gone, {counts['redirected']} redirected")
        for r in results:
            if r["category"] != "healthy":
                print(f"  ⚠️  [{r['category']}] {r['url']}: {r['details']}")
    return 1 if has_issues else 0


if __name__ == "__main__":
    sys.exit(main())
