#!/usr/bin/env python3
"""Prioritize wiki pages for verification.

Scores all pages using a weighted formula and outputs a ranked table.
The LLM reads the output and selects candidates for verification.

Usage:
  python3 sprue/scripts/prioritize.py                    # All pages, top 20
  python3 sprue/scripts/prioritize.py --top 5            # Top 5
  python3 sprue/scripts/prioritize.py --page kafka       # Score a single page
  python3 sprue/scripts/prioritize.py --tier critical    # Filter by risk tier
  python3 sprue/scripts/prioritize.py --json             # Machine-readable output

Output: ranked table of pages with priority scores and component breakdown.
"""

import sys, math, json, yaml
from pathlib import Path
from datetime import datetime
from collections import defaultdict

sys.path.insert(0, str(Path(__file__).resolve().parent))
from config import load as load_config

MANIFEST = Path("wiki/.index/manifest.yaml")
BY_SLUG_RAWS = Path("wiki/.index/by-slug-raws.yaml")
VERIFICATIONS = Path("instance/state/verifications.yaml")

# ── Static score maps ────────────────────────────────────────

RISK_SCORES = {"critical": 100, "operational": 70, "conceptual": 40, "reference": 10}
DECAY_SCORES = {"fast": 100, "medium": 60, "stable": 30, "glacial": 10}
TYPE_MULTIPLIERS = {
    "comparison": 1.3, "pattern": 1.2, "concept": 1.1,
    "entity": 1.0, "recipe": 0.9, "reference": 0.8,
    "decision": 0.7, "opinion": 0.7, "question": 0.6,
}


def _load_verify_config():
    """Load verify weights from instance/config.yaml."""
    cfg = load_config()
    verify = cfg.get("verify", {})
    weights = verify.get("weights", {})
    w = {
        "risk": weights.get("risk", 0.30),
        "freshness": weights.get("freshness", 0.35),
        "decay": weights.get("decay", 0.15),
        "impact": weights.get("impact", 0.15),
        "source": weights.get("source", 0.05),
    }
    cooldown = verify.get("cooldown_days", 30)
    return w, cooldown


def load_manifest():
    """Load wiki manifest, stripping _meta."""
    if not MANIFEST.exists():
        print("Error: manifest.yaml not found. Run: python3 sprue/scripts/build-index.py", file=sys.stderr)
        sys.exit(1)
    m = yaml.safe_load(MANIFEST.read_text()) or {}
    m.pop("_meta", None)
    return m


def build_wiki_to_raw():
    """Load reverse index: wiki slug → list of raw file paths.

    Reads the derived index at wiki/.index/by-slug-raws.yaml (generated by
    sprue/scripts/build-index.py). The index reflects the current manifest;
    orphaned compilation rows are already filtered out at generation time.
    """
    if not BY_SLUG_RAWS.exists():
        return {}
    return yaml.safe_load(BY_SLUG_RAWS.read_text()) or {}


def load_verified_slugs(cooldown_days):
    """Load slugs verified within the cooldown window."""
    if not VERIFICATIONS.exists():
        return set()
    entries = yaml.safe_load(VERIFICATIONS.read_text()) or []
    if not entries:
        return set()
    recent = set()
    cutoff = datetime.now()
    for entry in entries:
        ts = entry.get("verified_at", "")
        if not ts:
            continue
        try:
            verified_date = datetime.fromisoformat(str(ts).replace("Z", "+00:00"))
            days_ago = (cutoff - verified_date.replace(tzinfo=None)).days
            if days_ago < cooldown_days:
                recent.add(entry.get("page", ""))
        except (ValueError, TypeError):
            continue
    return recent


def compute_inbound_links(manifest):
    """Build inbound link count from manifest links_to fields."""
    inbound = defaultdict(int)
    for slug, meta in manifest.items():
        for target in meta.get("links_to", []):
            inbound[target] += 1
    return inbound


def freshness_score(last_verified, half_life_days=180):
    """Score how urgently a page needs verification.

    Never-verified → 85 (high urgency but not maximum).
    Otherwise sigmoid from last_verified date.
    """
    if not last_verified or str(last_verified) == "null" or str(last_verified) == "None":
        return 85.0

    try:
        verified_date = datetime.fromisoformat(str(last_verified))
    except (ValueError, TypeError):
        return 85.0

    days_since = (datetime.now() - verified_date).days
    if days_since <= 0:
        return 0.0

    # Sigmoid: rises from 0 at verification to ~100 at 2x half-life
    k = 3.5 / half_life_days
    return min(100.0, 100.0 / (1.0 + math.exp(-k * (days_since - half_life_days))))


def impact_score(slug, inbound_links, page_type):
    """Score based on how many pages reference this one."""
    count = inbound_links.get(slug, 0)
    normalized = min(count / 50.0, 1.0) * 100.0
    multiplier = TYPE_MULTIPLIERS.get(page_type, 1.0)
    return min(100.0, normalized * multiplier)


def source_score(slug, wiki_to_raw):
    """Pages without raw sources need more scrutiny."""
    if slug in wiki_to_raw and wiki_to_raw[slug]:
        return 30.0  # Has raw file to verify against
    return 100.0  # Synthesized / no raw — higher priority


def score_page(slug, meta, weights, inbound_links, wiki_to_raw):
    """Compute priority score for a single page."""
    risk = RISK_SCORES.get(meta.get("risk_tier", "reference"), 10)
    fresh = freshness_score(meta.get("last_verified"))
    decay = DECAY_SCORES.get(meta.get("decay_tier", "stable"), 30)
    imp = impact_score(slug, inbound_links, meta.get("type", "entity"))
    src = source_score(slug, wiki_to_raw)

    total = (
        risk * weights["risk"]
        + fresh * weights["freshness"]
        + decay * weights["decay"]
        + imp * weights["impact"]
        + src * weights["source"]
    )

    return total, {
        "risk": risk,
        "freshness": round(fresh, 1),
        "decay": decay,
        "impact": round(imp, 1),
        "source": round(src, 1),
    }


def format_table(scored_pages, top_n):
    """Format scored pages as a human-readable table."""
    lines = []
    lines.append(f"Verification Priority — Top {min(top_n, len(scored_pages))} of {len(scored_pages)} candidates\n")
    lines.append(f" {'#':>3}  {'Page':<35} {'Risk':<13} {'Decay':<8} {'Score':>6}  {'Inbound':>7}  Signal")
    lines.append(f" {'─'*3}  {'─'*35} {'─'*13} {'─'*8} {'─'*6}  {'─'*7}  {'─'*30}")

    for i, (slug, score, components, meta) in enumerate(scored_pages[:top_n], 1):
        risk = meta.get("risk_tier", "?")
        decay = meta.get("decay_tier", "?")
        lv = meta.get("last_verified")
        verified_str = "never" if (not lv or str(lv) == "null") else str(lv)[:10]
        inbound = int(components["impact"] / TYPE_MULTIPLIERS.get(meta.get("type", "entity"), 1.0) * 50 / 100)

        signal_parts = []
        if verified_str == "never":
            signal_parts.append("never verified")
        else:
            signal_parts.append(f"verified {verified_str}")
        if components["impact"] >= 50:
            signal_parts.append(f"{inbound} inbound")

        lines.append(
            f" {i:>3}  {slug:<35} {risk:<13} {decay:<8} {score:>6.1f}  {inbound:>7}  {', '.join(signal_parts)}"
        )

    return "\n".join(lines)


def format_json(scored_pages, top_n):
    """Format scored pages as JSON."""
    results = []
    for slug, score, components, meta in scored_pages[:top_n]:
        results.append({
            "slug": slug,
            "score": round(score, 1),
            "risk_tier": meta.get("risk_tier", "unknown"),
            "decay_tier": meta.get("decay_tier", "unknown"),
            "type": meta.get("type", "unknown"),
            "last_verified": str(meta.get("last_verified", "null")),
            "dir": meta.get("dir", ""),
            "components": components,
        })
    return json.dumps(results, indent=2)


def main():
    args = sys.argv[1:]
    top_n = 20
    filter_page = None
    filter_tier = None
    output_json = False

    i = 0
    while i < len(args):
        if args[i] == "--top" and i + 1 < len(args):
            top_n = int(args[i + 1]); i += 2
        elif args[i] == "--page" and i + 1 < len(args):
            filter_page = args[i + 1]; i += 2
        elif args[i] == "--tier" and i + 1 < len(args):
            filter_tier = args[i + 1]; i += 2
        elif args[i] == "--json":
            output_json = True; i += 1
        else:
            i += 1

    weights, cooldown = _load_verify_config()
    manifest = load_manifest()
    inbound_links = compute_inbound_links(manifest)
    wiki_to_raw = build_wiki_to_raw()
    recently_verified = load_verified_slugs(cooldown)

    scored = []
    for slug, meta in manifest.items():
        if filter_page and slug != filter_page:
            continue
        if filter_tier and meta.get("risk_tier") != filter_tier:
            continue
        if slug in recently_verified and not filter_page:
            continue

        score, components = score_page(slug, meta, weights, inbound_links, wiki_to_raw)
        scored.append((slug, score, components, meta))

    scored.sort(key=lambda x: -x[1])

    if output_json:
        print(format_json(scored, top_n))
    else:
        print(format_table(scored, top_n))


if __name__ == "__main__":
    main()
